# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-09 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initadmin', '0002_userconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfig',
            name='scope',
            field=models.CharField(choices=[('eu', 'Europe'), ('eu-at', 'Europe/Austria'), ('eu-be', 'Europe/Belgium'), ('eu-bg', 'Europe/Bulgaria'), ('eu-hr', 'Europe/Croatia'), ('eu-cy', 'Europe/Cyprus'), ('eu-cz', 'Europe/Czech Republic'), ('eu-dk', 'Europe/Denmark'), ('eu-ee', 'Europe/Estonia'), ('eu-fi', 'Europe/Finland'), ('eu-fr', 'Europe/France'), ('eu-fr-paris', 'Europe/France/Paris'), ('eu-fr-lille', 'Europe/France/Lille'), ('eu-fr-toulouse', 'Europe/France/Toulouse'), ('eu-de', 'Europe/Germany'), ('eu-gr', 'Europe/Greece'), ('eu-hu', 'Europe/Hungary'), ('eu-ie', 'Europe/Ireland'), ('eu-it', 'Europe/Italy'), ('eu-lv', 'Europe/Latvia'), ('eu-lt', 'Europe/Lithuania'), ('eu-lu', 'Europe/Luxembourg'), ('eu-mt', 'Europe/Malta'), ('eu-nl', 'Europe/Netherlands'), ('eu-pl', 'Europe/Poland'), ('eu-pt', 'Europe/Portugal'), ('eu-ro', 'Europe/Romania'), ('eu-sk', 'Europe/Slovakia'), ('eu-si', 'Europe/Slovenia'), ('eu-es', 'Europe/Spain'), ('eu-se', 'Europe/Sweden'), ('eu-gb', 'Europe/United Kingdom')], default='eu', max_length=100),
        ),
    ]
