# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-14 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initadmin', '0003_userconfig_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfig',
            name='is_scope_confirmed',
            field=models.BooleanField(default=True),
        ),
    ]
