# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-22 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initadmin', '0004_userconfig_is_scope_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfig',
            name='is_flagged',
            field=models.CharField(default='', max_length=200),
        ),
    ]
