# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-22 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initadmin', '0005_userconfig_is_flagged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfig',
            name='is_flagged',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
