# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-09 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initproc', '0027_merge_20180624_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='bereich',
            field=models.CharField(choices=[('Global Politics & International Cooperation', 'Global Politics & International Cooperation'), ('Education, Research & Culture', 'Education, Research & Culture'), ('Interior Politics', 'Interior Politics'), ('Net- & Media Politics', 'Net- & Media Politics'), ('Gender Equality', 'Gender Equality'), ('Diversity & Integration', 'Diversity & Integration'), ('Democracy & Transparency', 'Democracy & Transparency'), ('Health, Nutrition, Consumer Protection', 'Health, Nutrition, Consumer Protection'), ('Environment, Mobility, Infrastructural Development', 'Environment, Mobility, Infrastructural Development'), ('Social Justice, Economy, Work & Finance', 'Social Justice, Economy, Work & Finance'), ('Other', 'Other')], max_length=60),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='ebene',
            field=models.CharField(choices=[('eu', 'Europe'), ('eu-at', 'Europe/Austria'), ('eu-be', 'Europe/Belgium'), ('eu-bg', 'Europe/Bulgaria'), ('eu-hr', 'Europe/Croatia'), ('eu-cy', 'Europe/Cyprus'), ('eu-cz', 'Europe/Czech Republic'), ('eu-dk', 'Europe/Denmark'), ('eu-ee', 'Europe/Estonia'), ('eu-fi', 'Europe/Finland'), ('eu-fr', 'Europe/France'), ('eu-fr-paris', 'Europe/France/Paris'), ('eu-fr-lille', 'Europe/France/Lille'), ('eu-fr-toulouse', 'Europe/France/Toulouse'), ('eu-de', 'Europe/Germany'), ('eu-gr', 'Europe/Greece'), ('eu-hu', 'Europe/Hungary'), ('eu-ie', 'Europe/Ireland'), ('eu-it', 'Europe/Italy'), ('eu-lv', 'Europe/Latvia'), ('eu-lt', 'Europe/Lithuania'), ('eu-lu', 'Europe/Luxembourg'), ('eu-mt', 'Europe/Malta'), ('eu-nl', 'Europe/Netherlands'), ('eu-pl', 'Europe/Poland'), ('eu-pt', 'Europe/Portugal'), ('eu-ro', 'Europe/Romania'), ('eu-sk', 'Europe/Slovakia'), ('eu-si', 'Europe/Slovenia'), ('eu-es', 'Europe/Spain'), ('eu-se', 'Europe/Sweden'), ('eu-gb', 'Europe/United Kingdom')], max_length=100),
        ),
    ]
