# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-26 18:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('initproc', '0028_auto_20180710_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=1024)),
                ('description', models.TextField(blank=True)),
                ('challenge', models.TextField(blank=True)),
                ('demand', models.TextField(blank=True)),
                ('expected_cost', models.TextField(blank=True)),
                ('proposed_financing', models.TextField(blank=True)),
                ('methodology', models.TextField(blank=True)),
                ('initial_argument', models.TextField(blank=True)),
                ('context', models.CharField(max_length=60)),
                ('scope', models.CharField(max_length=60)),
                ('topic', models.CharField(max_length=60)),
                ('state', models.CharField(choices=[('draft', 'in preparation'), ('deleted', 'deleted'), ('staged', 'staged')], default='draft', max_length=20)),
                ('eligible_voters', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staged_at', models.DateTimeField(auto_now=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('was_validated_at', models.DateField(blank=True, null=True)),
                ('went_in_discussion_at', models.DateField(blank=True, null=True)),
                ('went_in_vote_at', models.DateField(blank=True, null=True)),
                ('was_published_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'permissions': [('policy_create', 'Can create new policy'), ('policy_edit', 'Can edit policy'), ('policy_delete', 'Can delete policy'), ('policy_submit', 'Can submit policy')],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='contra',
            name='initiative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contras', to='initproc.Initiative'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='bereich',
            field=models.CharField(choices=[('smart_state', 'Smart State'), ('economic_renaissance', 'Economic Rennaisance'), ('social_equalty', 'Social Equality'), ('global_balance', 'Global Balance'), ('citizen_empowerment', 'Citizen Empowerment'), ('eu_reform', 'EU Reform')], max_length=60),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='einordnung',
            field=models.CharField(choices=[('finance', 'Finance'), ('foreign_policy', 'Foreign Policy'), ('domestic_policy', 'Domestic Policy'), ('economy', 'Economy'), ('energy', 'Energy'), ('justice_consumer_protection', 'Justice and Consumer Protection'), ('labor_social_welfare', 'Labor and Social Welfare'), ('defense', 'Defense'), ('agriculture', 'Agriculture'), ('family_affairs', 'Family Affairs'), ('health', 'Health'), ('transport_digital_infrastructure', 'Transport and Digital Infrastructure'), ('environmental_protection', 'Environmental Protection'), ('education_research', 'Education and Research'), ('economic_cooperation_development', 'Economic Cooperation and Development')], max_length=50),
        ),
        migrations.AlterField(
            model_name='moderation',
            name='initiative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderations', to='initproc.Initiative'),
        ),
        migrations.AlterField(
            model_name='moderation',
            name='vote',
            field=models.CharField(choices=[('n', 'no'), ('y', 'ok'), ('a', 'abstain'), ('r', 'request')], max_length=1),
        ),
        migrations.AlterField(
            model_name='pro',
            name='initiative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pros', to='initproc.Initiative'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='initiative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='initproc.Initiative'),
        ),
        migrations.AlterField(
            model_name='supporter',
            name='initiative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supporting_initiative', to='initproc.Initiative'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='initiative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='initproc.Initiative'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.IntegerField(choices=[('0', 'No'), ('1', 'Yes'), ('2', 'Abstain')]),
        ),
        migrations.AddField(
            model_name='policy',
            name='supporters',
            field=models.ManyToManyField(through='initproc.Supporter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policy',
            name='variant_of',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='initproc.Policy'),
        ),
        migrations.AddField(
            model_name='contra',
            name='policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contras', to='initproc.Policy'),
        ),
        migrations.AddField(
            model_name='moderation',
            name='policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderations', to='initproc.Policy'),
        ),
        migrations.AddField(
            model_name='pro',
            name='policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pros', to='initproc.Policy'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='initproc.Policy'),
        ),
        migrations.AddField(
            model_name='supporter',
            name='policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supporting_policy', to='initproc.Policy'),
        ),
        migrations.AddField(
            model_name='vote',
            name='policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policy_votes', to='initproc.Policy'),
        ),
        migrations.AlterUniqueTogether(
            name='supporter',
            unique_together=set([('user', 'initiative', 'policy')]),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('user', 'initiative', 'policy')]),
        ),
    ]
