# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-28 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initproc', '0029_auto_20180826_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contra',
            name='initiative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_contras', to='initproc.Initiative'),
        ),
        migrations.AlterField(
            model_name='contra',
            name='policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policy_contras', to='initproc.Policy'),
        ),
        migrations.AlterField(
            model_name='moderation',
            name='initiative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_moderations', to='initproc.Initiative'),
        ),
        migrations.AlterField(
            model_name='moderation',
            name='policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policy_moderations', to='initproc.Policy'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='scope',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pro',
            name='initiative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_pros', to='initproc.Initiative'),
        ),
        migrations.AlterField(
            model_name='pro',
            name='policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policy_pros', to='initproc.Policy'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='initiative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_proposals', to='initproc.Initiative'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policy_proposals', to='initproc.Policy'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='initiative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_votes', to='initproc.Initiative'),
        ),
    ]
