# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-09-26 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initproc', '0031_auto_20180911_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderation',
            name='flags',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
