# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-09-29 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initproc', '0032_moderation_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='was_rejected_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
