# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-07 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initproc', '0033_policy_was_rejected_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='was_challenged_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
