# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-12 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initproc', '0034_policy_was_challenged_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'permissions': [('policy_create', 'Can create new policy'), ('policy_edit', 'Can edit policy'), ('policy_delete', 'Can delete policy'), ('policy_submit', 'Can submit policy'), ('policy_invite', 'Can invite others to co-initiate/support'), ('policy_stage', 'Can stage a policy'), ('policy_validate', 'Can validate a policy'), ('policy_invalidate', 'Can invalidate a policy'), ('policy_finalise', 'Can finalise a policy'), ('policy_discuss', 'Can move a policy into discussion')]},
        ),
        migrations.AddField(
            model_name='proposal',
            name='stale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='policy',
            name='state',
            field=models.CharField(choices=[('draft', 'in preparation'), ('deleted', 'deleted'), ('staged', 'staged'), ('submitted', 'submitted'), ('invalidated', 'invalidated'), ('rejected', 'rejected'), ('closed', 'closed'), ('hidden', 'hidden'), ('challenged', 'challenged'), ('validated', 'validated'), ('supported', 'supported'), ('finalised', 'finalised'), ('discussed', 'discussed')], default='draft', max_length=20),
        ),
    ]
