# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-11-01 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initproc', '0035_auto_20181013_0057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'permissions': [('policy_create', 'Can create new policy'), ('policy_edit', 'Can edit policy'), ('policy_delete', 'Can delete policy'), ('policy_submit', 'Can submit policy'), ('policy_invite', 'Can invite others to co-initiate/support'), ('policy_stage', 'Can stage a policy'), ('policy_validate', 'Can validate a policy'), ('policy_invalidate', 'Can invalidate a policy'), ('policy_finalise', 'Can finalise a policy'), ('policy_discuss', 'Can move a policy into discussion'), ('policy_review', 'Can move a policy into final review')]},
        ),
        migrations.AlterField(
            model_name='policy',
            name='challenge',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='policy',
            name='demand',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='policy',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='policy',
            name='expected_cost',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='policy',
            name='initial_argument',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='policy',
            name='methodology',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='policy',
            name='proposed_financing',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='policy',
            name='state',
            field=models.CharField(choices=[('draft', 'in preparation'), ('deleted', 'deleted'), ('staged', 'staged'), ('submitted', 'submitted'), ('invalidated', 'invalidated'), ('rejected', 'rejected'), ('closed', 'closed'), ('hidden', 'hidden'), ('challenged', 'challenged'), ('validated', 'validated'), ('supported', 'supported'), ('finalised', 'finalised'), ('discussed', 'in discussion'), ('reviewed', 'in review')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='policy',
            name='subtitle',
            field=models.CharField(max_length=1024),
        ),
    ]
