# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-11-10 08:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initproc', '0036_auto_20181101_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moderation',
            old_name='flags',
            new_name='blockers',
        ),
    ]
