# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-11-10 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initproc', '0037_auto_20181110_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='was_challenged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='was_published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='was_rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='was_validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='went_in_discussion_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='went_in_vote_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
