# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-11-11 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initproc', '0038_auto_20181110_2318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policy',
            old_name='staged_at',
            new_name='was_staged_at',
        ),
        migrations.AddField(
            model_name='policy',
            name='was_reopened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
