# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-24 17:05
from __future__ import unicode_literals

from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('initproc', '0042_auto_20181124_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, autocomplete_view='policy_tags_autocomplete', help_text='Enter a comma-separated tag string', initial='', space_delimiter=False, to='initproc.Tag', tree=True),
        ),
    ]
